name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Upload image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/helloworldaws:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/helloworldaws:latest

      - name: Connect SSH and Deploy EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/helloworldaws:latest
            echo "Stopping and removing old container..."
            docker stop helloworldaws || true
            docker rm helloworldaws || true
            echo "Running new container..."
            docker run -d -p 80:80 --name helloworldaws ${{ secrets.DOCKERHUB_USERNAME }}/helloworldaws:latest
